export default function TrendsAIPage() {
  return (
    <section className="space-y-6">
      <h1 className="text-3xl font-bold">📊 Macro Analysis (Trends AI)</h1>
      <p className="text-gray-600">
        This module summarizes macroeconomic indicators and trends using LLMs.
      </p>

      <div className="grid md:grid-cols-2 gap-6">
        <div className="bg-white p-6 rounded-xl shadow">
          <h2 className="font-semibold text-lg mb-2">📈 Inflation Trends</h2>
          <p className="text-sm text-gray-700">LLM summary of inflation data...</p>
        </div>
        <div className="bg-white p-6 rounded-xl shadow">
          <h2 className="font-semibold text-lg mb-2">💼 GDP Forecast</h2>
          <p className="text-sm text-gray-700">GDP predictions generated by the model...</p>
        </div>
      </div>
    </section>
  )
}
